# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("#Dialog{\n"
"    border-image:url(:/assets/subWidget.png)\n"
"}")
        self.image = QtWidgets.QLabel(Dialog)
        self.image.setGeometry(QtCore.QRect(36, 18, 571, 341))
        self.image.setStyleSheet("border-radius:30px;\n"
"border-width:10px;\n"
"border-color:white;")
        self.image.setText("")
        self.image.setObjectName("image")
        self.buttonOk = QtWidgets.QPushButton(Dialog)
        self.buttonOk.setGeometry(QtCore.QRect(380, 428, 93, 41))
        self.buttonOk.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgba(255,255,255,128); /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: white;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:white; /*字体颜色*/\n"
"    font-family:\'等线\';\n"
"    padding: 5px;\n"
"    outline:none;\n"
"\n"
"}")
        self.buttonOk.setObjectName("buttonOk")
        self.buttonCancel = QtWidgets.QPushButton(Dialog)
        self.buttonCancel.setGeometry(QtCore.QRect(490, 428, 93, 40))
        self.buttonCancel.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgba(255,255,255,128); /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: white;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:white; /*字体颜色*/\n"
"    font-family:\'等线\';\n"
"    padding: 5px;\n"
"    outline:none;\n"
"\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.load_button = QtWidgets.QPushButton(Dialog)
        self.load_button.setGeometry(QtCore.QRect(270, 428, 93, 41))
        self.load_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgba(255,255,255,128); /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: white;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:white; /*字体颜色*/\n"
"    font-family:\'等线\';\n"
"    padding: 5px;\n"
"    outline:none;\n"
"\n"
"}")
        self.load_button.setObjectName("load_button")
        self.inputName = QtWidgets.QLineEdit(Dialog)
        self.inputName.setGeometry(QtCore.QRect(130, 380, 451, 31))
        self.inputName.setStyleSheet("#inputName{\n"
"    background-color:rgba(255,255,255,180);\n"
"    border:none\n"
"}")
        self.inputName.setObjectName("inputName")
        self.labelTip = QtWidgets.QLabel(Dialog)
        self.labelTip.setGeometry(QtCore.QRect(30, 430, 231, 31))
        self.labelTip.setStyleSheet("font-weight:bold;\n"
"font-family:\'等线\';\n"
"font-size:20px;")
        self.labelTip.setObjectName("labelTip")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonOk.setText(_translate("Dialog", "确定"))
        self.buttonCancel.setText(_translate("Dialog", "取消"))
        self.load_button.setText(_translate("Dialog", "上传"))
        self.labelTip.setText(_translate("Dialog", "tishi"))
